corrected_d_o = {
    'A.J. (Apostles of Jesus)': 'Apostles of the Sacred Heart of Jesus',
    'Franciscan Friars of the Atonement': 'Atonement Friars',
    'Augustine': 'Augustinian',
    'Augustinian Friars': 'Augustinian',
    'Augustinian Recollects': 'Augustinian',
    'Augustinians of the Assumption': 'Augustinian',
    'O.S.A. (Augustinian)': 'Augustinian',
    'Order of St. Augustine': 'Augustinian',
    'Basilian (C.S.B.)': 'Basilian',
    'Basilian Fathers, Salvatorian b.s.o.': 'Basilian',
    'OSB  Benedictine': 'Benedictine',
    'OSB--Benedictine': 'Benedictine',
    'Order of St. Benedict (OSB)': 'Benedictine',
    'Bro.of Sacred Heart': 'Brothers of the Sacred Heart',
    'Brothers of Sacred Heart': 'Brothers of the Sacred Heart',
    'SC--Brothers of the Sacred Heart': 'Brothers of the Sacred Heart',
    'S.C.  Brothers of the Sacred Heart': 'Brothers of the Sacred Heart',
    'S.C. (Brothers of the Sacred Heart)': 'Brothers of the Sacred Heart',
    'Bros Christian School': 'Brothers of the Christian Schools',
    'Bros of Christian School': 'Brothers of the Christian Schools',
    'Bros. Christian School': 'Brothers of the Christian Schools',
    'Brothers of Christian Schools': 'Brothers of the Christian Schools',
    'Brothers of the Christian School': 'Brothers of the Christian Schools',
    'FSC - Brothers of the Christian Schools': 'Brothers of the Christian Schools',
    'FSC Brothers of the Christian Schools': 'Brothers of the Christian Schools',
    'Brothers of Holy Cross of Texas': 'Brothers of the Holy Cross',
    'CSC': 'Brothers of the Holy Cross',
    'Sisters of Charity of Nazareth': 'Sisters of Charity',
    'C.F.C.  Congregation of Christian Brothers': 'Congregation of the Christian Brothers',
    'CFC - Congregation of Christian Brothers': 'Congregation of the Christian Brothers',
    'CFC - Congregation of the Christian Brothers': 'Congregation of the Christian Brothers',
    'CFC - Congregation of Christian': 'Congregation of the Christian Brothers',
    'Christian Brothers': 'Congregation of the Christian Brothers',
    'C.M.F.  Claretian Missionaries': 'Claretian Missionaries',
    'CMF-- Claretians': 'Claretian Missionaries',
    'Claretian': 'Claretian Missionaries',
    'C.R. Congregation of the Resurrection': 'Congregation of the Resurrerction',
    'Resurrectionist': 'Congregation of the Resurrerction',
    'C.S.Sp. (Spiritan)': 'Spiritan',
    'CFX Brothers  of St. Francis Xavier': 'Brothers of St. Francis Xavier',
    'Capuchin': 'Capuchin Franciscan',
    'Capuchin Friar': 'Capuchin Franciscan',
    'Capuchine  OFM, CAP': 'Capuchin Franciscan',
    'Capuchins': 'Capuchin Franciscan',
    'o.f.m.cap  Capuchin': 'Capuchin Franciscan',
    'ofm cap': 'Capuchin Franciscan',
    'O.F.M.': 'Franciscan',
    'O.F.M.Conv.': 'Conventual Franciscan',
    'OFM Cap.': 'Capuchin Franciscan',
    'OFM.Cap': 'Capuchin Franciscan',
    'OFM.Cap.': 'Capuchin Franciscan',
    'OFM Cap Capuchin': 'Capuchin Franciscan',
    'OFM Capuchin': 'Capuchin Franciscan',
    'OFM. Conv.': 'Conventual Franciscan',
    'Viatorian Fathers--Les Clers de Saint-Viateur': 'Clerics of St. Viator',
    'Cong. of Sacred Heart of Jesus and Mary': 'Congregation of the Sacred Hearts of Jesus and Mary',
    'Congregation of Holy Cross': 'Congregation of the Holy Cross',
    'Congregation of the Sacred Hearts': 'Congregation of the Sacred Hearts of Jesus and Mary',
    'Sacred Hearts': 'Congregation of the Sacred Hearts of Jesus and Mary',
    'SS.CC.': 'Congregation of the Sacred Hearts of Jesus and Mary',
    'Congregation of Priests of the Sacred Heart': 'Congregation of the Priests of the Sacred Heart',
    'Priests of the Sacred Heart  S.C.J.': 'Congregation of the Priests of the Sacred Heart',
    'Priests of the Sacred Heart. S.C.J.': 'Congregation of the Priests of the Sacred Heart',
    'Sacred Heart': 'Congregation of the Priests of the Sacred Heart',
    'Dicoesan': 'Diocesan',
    'Diocesan.': 'Diocesan',
    'Diocese': 'Diocesan',
    'Diocesen': 'Diocesan',
    'Dioscean': 'Diocesan',
    'Coventual Franciscan': 'Conventual Franciscan',
    'Crosier':  'Crosier Fathers',
    'Crosier Fathers':  'Crosier Fathers',
    'O.S.C.  Crosier': 'Crosier Fathers',
    'OFM  Franciscan': 'Franciscan',
    'OFM Franciscan': 'Franciscan',
    'OFM Franciscans': 'Franciscan',
    'OSF  Franciscan Brothers of Brooklyn': 'Franciscan',
    'OSF': 'Franciscan',
    'Sisters of St Francis of the Holy Family (OSF)': 'Franciscan',
    'T.O.R. (Franciscan)': 'Tertius Ordo Regularis S. Francisci',
    'T.O.R. Franciscans': 'Tertius Ordo Regularis S. Francisci',
    'Divine Word Miss.': 'Divine Word Missionaries',
    'SDV--Divine Word Missionaries': 'Divine Word Missionaries',
    'Society of the Divine Word': 'Divine Word Missionaries',
    'Society of the Divine Word (SVD)': 'Divine Word Missionaries',
    'OP': 'Dominican',
    'Dominican Sisters': 'Dominican',
    'Dominican Sisters of the Third Order of St. Dominic': 'Dominican',
    'O.P.  Dominican': 'Dominican',
    'Edmundite': 'Society of St. Edmund',
    'F.M.S. Marist Brothers': 'Marist Brothers',
    'FMS (The Marist Brothrs)': 'Marist Brothers',
    'Marist': 'Marist Brothers',
    'Father of the Holy Ghost (Irish Spritans)': 'Congregation of the Holy Spirit',
    'Holy Ghost Fathers': 'Congregation of the Holy Spirit',
    'Holy Spirit': 'Congregation of the Holy Spirit',
    'Francisan': 'Franciscan',
    'Franciscan OFM Conv': 'Ordo Fratum Minorum',
    'Franciscans': 'Franciscan',
    'Holy Cross Father': 'Holy Cross Fathers',
    'm.s.f.  Holy Family': 'Holy Family of Nazareth',
    'Inst. Christ the King': 'Institute of Christ the King',
    'Jesuit - Irish Province': 'Jesuit',
    'Jesuit ?': 'Jesuit',
    'Jesuit??': 'Jesuit',
    'Jesuits': 'Jesuit',
    'S.J.   Jesuit': 'Jesuit',
    'S.J.  Jesuit': 'Jesuit',
    'S.J. (Jesuit)': 'Jesuit',
    'SJ  Jesuit': 'Jesuit',
    'SJ': 'Jesuit',
    'S.J.': 'Jesuit',
    'Josephite': 'Josephite Fathers',
    'Josephite Father': 'Josephite Fathers',
    'LaSalle Christian Brother': 'De La Salle Christian Brothers',
    'LaSallette': 'De La Salle Christian Brothers',
    'Legionaires of Christ': 'Legion of Christ',
    'Legionnaires of Christ': 'Legion of Christ',
    'Little Brothers of the Good Shepard': 'Little Brothers of the Good Shepherd',
    'Little Brothers of the Good Shepherd (LBGS)': 'Little Brothers of the Good Shepherd',
    'M.AFR.   Society of Missionaries in Africa': 'Society of African Missions',
    'Society of African Missions': 'Society of African Missions',
    'W.F. Missionaries of Africa': 'Society of African Missions',
    'M.S.': 'Marianist Sisters',
    'MM  Maryknoll Mission': 'Maryknoll',
    'Maryknoll Missionary': 'Maryknoll',
    'Marian': 'Marianist',
    'Marinist': 'Marianist',
    'Marian Fathers': 'Marianist Fathers',
    'Missionaries of Holy Spirit': 'Missionaries of the Holy Spirit',
    'Missionary Oblates of Mary Imaculate of Texas': 'Oblates of Mary Immaculate',
    'O.M.I.  Oblate': 'Oblates of Mary Immaculate',
    'Oblate': 'Oblates of Mary Immaculate',
    'Oblates': 'Oblates of Mary Immaculate',
    'Oblates - OMI': 'Oblates of Mary Immaculate',
    'Oblates of Mary Immaculate': 'Oblates of Mary Immaculate',
    'Oblates OMV': 'Oblates of the Virgin Mary',
    'Oblates St. Francis de Sales': 'Oblates of St. Francis de Sales',
    'Oblates of St. Franis de Sales': 'Oblates of St. Francis de Sales',
    'S.T. Missionary Servants of the Most Holy Trinity': 'Missionary Servants of the Most Holy Trinity',
    'S.T. (Trinatarian)': 'Missionary Servants of the Most Holy Trinity',
    'Missionary Servants of Most Holy Trinity': 'Missionary Servants of the Most Holy Trinity',
    'Trinitarian': 'Missionary Servants of the Most Holy Trinity',
    'Missionary Sisters of the Sacred Heart of Jesus aka The Cabrini Sisters': 'Missionary Sisters of the Sacred Heart of Jesus',
    'Norbertines': 'Norbertine',
    'O.S.A. (Augustinian)': 'Augustinian',
    'O.S.B.': 'Benedictine',
    'OSB': 'Benedictine',
    'Order of St. Benedict (OSB)': 'Benedictine',
    'OSM  Servite': 'Order of Friar Servants of Mary',
    'Servite': 'Order of Friar Servants of Mary',
    'Order of St. Augustine': 'Augustinian',
    'Pallatine Sisters': 'Pallottine',
    'Pallotine': 'Pallottine',
    'Pallottines': 'Pallottine',
    'S,A.C.   Pallottine': 'Pallottine',
    'Pauline Fathers (o.s.p.p.e)': 'Paulinen Fathers',
    'Redemptorists': 'Redemptorist',
    'S.D.S.  Salvatorian': 'Salvatorian',
    'Salesians': 'Salesian',
    'Salesians of Don Bosco': 'Salesian',
    'Scalabrinian Fathers': 'Scalabrinian',
    'Scalabrinian--Congregation of Missionary Fathers of St. Charles': 'Scalabrinian',
    'Scalabrinian--Missionaries of St. Charles': 'Scalabrinian',
    'Scalabrinians': 'Scalabrinian',
    'Servants of Paraclete': 'Servants of the Paraclete',
    'Soc. Precious Blood': 'Society of the Precious Blood',
    'Society  of the Precious Blood': 'Society of the Precious Blood',
    'Society of Precious Blood': 'Society of the Precious Blood',
    'Precious Blood': 'Society of the Precious Blood',
    'Society of Holy Child Jesus': 'Society of the Holy Child Jesus',
    'Theatine Fathers': 'Theatine',
    'Trappist/Cistercian': 'Trappist',
    'Vicentian (C.M.)': 'Vincetian',
    'Vincentian Fathers': 'Vincetian',
    'Vincentians': 'Vincetian',
    'Xaverian Brothers': 'Xaverian',
    'Xaverian Missionary Fathers': 'Xaverian',
    'order?': 'Unknown'
}